#!/usr/bin/env python3
"""Build and run the Juliet CWE457 testcases on the vcml-pydrofoil VP.

Every testcase yields two elfs, one running its bad() half and one its good()
half, so that a fault in one cannot keep the other from being observed.

The two phases need different environments: building needs the poison LLVM
toolchain (glibc >= 2.39, so a container on older hosts), running needs podman
for the VP image. tools/juliet/run_suite.sh wires both together.

    juliet_suite.py --list
    juliet_suite.py --build-only --filter '*_01'
    juliet_suite.py --run-only   --filter '*_01'
"""

import argparse
import csv
import fnmatch
import os
import re
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ZEPHYR_DIR = REPO / "sw" / "zephyr"
APP = "juliet"
SUITE = "CWE457_Use_of_Uninitialized_Variable"
PHASES = ("bad", "good")

CASE_RE = re.compile(rf"^{SUITE}__(?P<category>.+)_(?P<variant>\d\d)(?P<part>[ab]?)\.c$")
# Unanchored: a testcase may leave an unterminated line before the marker.
PHASE_RE = re.compile(r"VP-PHASE: (\w+)")
RESULT_RE = re.compile(r"VP-RESULT: (\w+) addr=(\S+) mcause=(\d+)")


@dataclass
class Case:
    category: str
    variant: str
    files: list = field(default_factory=list)

    @property
    def name(self):
        return f"{self.category}_{self.variant}"

    @property
    def entry(self):
        return f"{SUITE}__{self.name}"

    def expected(self, phase):
        # mpoison instruments the stack only, so the heap categories must not
        # fault -- they are the negative control. good() never should.
        if phase == "good" or "_malloc_" in self.category:
            return "CLEAN"
        return "POISON"


def discover(juliet_root):
    grouped = {}
    for path in sorted((juliet_root / "testcases" / SUITE).glob("s*/*.c")):
        m = CASE_RE.match(path.name)
        if m:
            grouped.setdefault((m["category"], m["variant"]), []).append(path)
    return [Case(cat, var, files) for (cat, var), files in sorted(grouped.items())]


def case_source(case, phase, juliet_root):
    includes = "\n".join(
        f'#include "{f.relative_to(juliet_root / "testcases").as_posix()}"'
        for f in case.files
    )
    return f"""/* Generated by tools/juliet/juliet_suite.py -- do not edit. */

{includes}

const char *juliet_case_name = "{case.name}";
const char *juliet_phase = "{phase}";

void juliet_run(void)
{{
\t{case.entry}_{phase}();
}}
"""


def configure(board, fresh):
    """Bring up the one build directory every testcase is then built in."""
    build_dir = ZEPHYR_DIR / "workspace" / "zephyr" / "build" / f"{APP}-{board}"
    if fresh and build_dir.exists():
        shutil.rmtree(build_dir)
    if not (build_dir / "build.ninja").exists():
        subprocess.run([str(ZEPHYR_DIR / "build.sh"), APP, board],
                       cwd=ZEPHYR_DIR, check=True)
    return build_dir


def build_unit(case, phase, build_dir, juliet_root, elf_dir):
    (build_dir / "juliet_case.c").write_text(case_source(case, phase, juliet_root))
    proc = subprocess.run(["ninja", "-C", str(build_dir)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        return proc.stdout + proc.stderr
    shutil.copy(build_dir / "zephyr" / "zephyr.elf",
                elf_dir / f"{case.name}.{phase}.elf")
    return None


def write_cfg(key, template, cfg_path):
    elf = f"${{dir}}/../elf/{key}.elf"
    out = []
    for line in template.splitlines():
        field_name = line.split("=", 1)[0].strip()
        if field_name in ("system.core.symbols", "system.core.elf",
                          "system.loader.images"):
            out.append(f"{field_name} = {elf}")
        elif field_name == "system.name":
            out.append(f"system.name = juliet {key}")
        else:
            out.append(line)
    cfg_path.write_text("\n".join(out) + "\n")


def run_unit(key, results, template, image, timeout):
    cfg = results / "cfg" / f"{key}.cfg"
    write_cfg(key, template, cfg)
    cmd = ["podman", "run", "--rm", "--userns", "keep-id",
           "--security-opt", "label=disable", "-v", f"{REPO}:/configs:ro",
           image, str(cfg.relative_to(REPO))]
    started = time.time()
    # A run that normally takes seconds can stall under load; retry once so a
    # flake does not read as a result.
    for attempt in (1, 2):
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True,
                                  timeout=timeout)
            output, rc, timed_out = proc.stdout + proc.stderr, proc.returncode, False
        except subprocess.TimeoutExpired as exc:
            output = (exc.stdout or b"").decode(errors="replace")
            rc, timed_out = -1, True
        outcome, detail = classify(rc, output, timed_out)
        if outcome != "TIMEOUT" or attempt == 2:
            break
    (results / "logs" / f"{key}.log").write_text(output)
    return outcome, detail, rc, time.time() - started


def classify(rc, output, timed_out):
    if timed_out:
        return "TIMEOUT", ""
    phases = PHASE_RE.findall(output)
    last = phases[-1] if phases else "none"
    result = RESULT_RE.search(output)
    if result:
        return ("POISON" if result.group(1) == "POISON" else "FAULT"), result.group(0)
    if rc == 0 and last == "done":
        return "CLEAN", ""
    if rc == 0:
        return "HANG", f"last phase: {last}"
    return "ERROR", f"exit {rc}, last phase: {last}"


def merge_results(path, rows):
    """Keep rows of testcases this run did not cover, so a filtered rerun does
    not throw away the rest of the report."""
    fields = list(rows[0])
    merged = {}
    if path.exists():
        with path.open(newline="") as fh:
            for old in csv.DictReader(fh):
                merged[old["key"]] = {f: old.get(f, "") for f in fields}
    for row in rows:
        merged[row["key"]] = row
    ordered = sorted(merged.values(), key=lambda r: r["key"])
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(ordered)
    return ordered


def report(records):
    variants = sorted({r["variant"] for r in records})
    categories = sorted({r["category"] for r in records})
    width = max(len(c) for c in categories)

    for phase in PHASES:
        by_key = {(r["category"], r["variant"]): r for r in records
                  if r["phase"] == phase}
        if not by_key:
            continue
        print(f"\nphase {phase}")
        print(f"{'category'.ljust(width)}  " + " ".join(v.rjust(2) for v in variants))
        for cat in categories:
            cells = []
            for var in variants:
                rec = by_key.get((cat, var))
                mark = "" if rec is None else {"PASS": "+", "FAIL": "-"}.get(
                    rec["verdict"], "?")
                cells.append(mark.rjust(2))
            print(f"{cat.ljust(width)}  " + " ".join(cells))
    print("\n  + expected   - unexpected\n")

    counts = {}
    for rec in records:
        key = (rec["phase"], rec["verdict"], rec["outcome"])
        counts[key] = counts.get(key, 0) + 1
    for (phase, verdict, outcome), n in sorted(counts.items()):
        print(f"  {phase:4}  {verdict:4}  {outcome:15} {n:4}")
    failed = [r for r in records if r["verdict"] != "PASS"]
    print(f"\n  {len(records) - len(failed)}/{len(records)} as expected")
    for rec in sorted(failed, key=lambda r: r["key"]):
        print(f"    {rec['key']}: expected {rec['expected']}, got {rec['outcome']} "
              f"{rec['detail']}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--filter", default="*", help="fnmatch pattern on the case name")
    ap.add_argument("--phase", choices=PHASES, help="only one half of each testcase")
    ap.add_argument("--board", default="pydrofoil_64")
    ap.add_argument("--build-only", action="store_true")
    ap.add_argument("--run-only", action="store_true")
    ap.add_argument("--jobs", type=int, default=4, help="parallel VP runs")
    ap.add_argument("--timeout", type=int, default=120, help="seconds per VP run")
    ap.add_argument("--no-fresh", action="store_true",
                    help="keep an existing build directory (see README)")
    ap.add_argument("--results", type=Path, default=REPO / "results" / "juliet")
    ap.add_argument("--image", default="localhost/vcml-pydrofoil:latest")
    ap.add_argument("--juliet-root", type=Path,
                    default=Path(os.environ.get("JULIET_ROOT",
                                                REPO / "juliet_test_suite")))
    ap.add_argument("--list", action="store_true", help="list cases and exit")
    args = ap.parse_args()

    # The VP reads its config through the repo mounted as /configs.
    args.results = Path(args.results)
    args.results = (args.results if args.results.is_absolute()
                    else REPO / args.results).resolve()
    if not args.results.is_relative_to(REPO):
        sys.exit(f"--results must be inside {REPO}")

    cases = [c for c in discover(args.juliet_root)
             if fnmatch.fnmatch(c.name, args.filter)]
    if not cases:
        sys.exit(f"no testcases match {args.filter!r}")
    if args.list:
        for case in cases:
            print(f"{case.name:55} bad={case.expected('bad'):6} "
                  f"{' '.join(f.name for f in case.files)}")
        print(f"\n{len(cases)} testcases")
        return

    phases = (args.phase,) if args.phase else PHASES
    units = [(c, p) for c in cases for p in phases]

    args.results.mkdir(parents=True, exist_ok=True)
    for sub in ("elf", "cfg", "logs"):
        (args.results / sub).mkdir(exist_ok=True)

    records = {}
    for case, phase in units:
        key = f"{case.name}.{phase}"
        records[key] = {"key": key, "name": case.name, "category": case.category,
                        "variant": case.variant, "phase": phase,
                        "expected": case.expected(phase), "outcome": "",
                        "verdict": "", "detail": "", "exit_code": "", "seconds": ""}

    if not args.run_only:
        if os.environ.get("ZEPHYR_TOOLCHAIN_VARIANT") != "llvm":
            sys.exit("ZEPHYR_TOOLCHAIN_VARIANT must be llvm; gcc emits no mpoison")
        build_dir = configure(args.board, fresh=not args.no_fresh)
        started = time.time()
        for i, (case, phase) in enumerate(units, 1):
            key = f"{case.name}.{phase}"
            error = build_unit(case, phase, build_dir, args.juliet_root,
                               args.results / "elf")
            if error:
                records[key].update(outcome="BUILD_FAIL", verdict="FAIL",
                                    detail=error.strip().splitlines()[-1][:200])
                (args.results / "logs" / f"{key}.build.log").write_text(error)
            print(f"[{i}/{len(units)}] build {key}{' FAILED' if error else ''}",
                  flush=True)
        print(f"built {len(units)} in {time.time() - started:.0f}s")

    if not args.build_only:
        runnable = []
        for case, phase in units:
            key = f"{case.name}.{phase}"
            if records[key]["outcome"] == "BUILD_FAIL":
                continue
            if (args.results / "elf" / f"{key}.elf").exists():
                runnable.append(key)
            else:
                records[key].update(outcome="NO_ELF", verdict="FAIL",
                                    detail="build phase did not produce an elf")
        template = (REPO / "benchmark" / "zephyr" / "juliet.cfg").read_text()
        started = time.time()

        def work(key):
            return key, run_unit(key, args.results, template, args.image,
                                 args.timeout)

        with ThreadPoolExecutor(max_workers=args.jobs) as pool:
            for i, (key, (outcome, detail, rc, secs)) in enumerate(
                    pool.map(work, runnable), 1):
                rec = records[key]
                rec.update(outcome=outcome, detail=detail, exit_code=rc,
                           seconds=f"{secs:.1f}",
                           verdict="PASS" if outcome == rec["expected"] else "FAIL")
                print(f"[{i}/{len(runnable)}] {rec['verdict']:4} {key} -> {outcome}",
                      flush=True)
        print(f"ran {len(runnable)} in {time.time() - started:.0f}s")

    rows = merge_results(args.results / "results.csv", list(records.values()))
    print(f"\nresults in {args.results.relative_to(REPO)}")

    if args.build_only:
        # Only a total build failure is worth stopping the wrapper for.
        failed = [r for r in rows if r["outcome"] == "BUILD_FAIL"]
        sys.exit(1 if len(failed) == len(rows) else 0)

    report(rows)
    sys.exit(1 if any(r["verdict"] == "FAIL" for r in rows) else 0)


if __name__ == "__main__":
    main()
